server:
  port: 8080


spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/Store"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
api:
  prefix: /api/v1
auth:
  token:
    expirationInMils: 3600000
    jwtSecret: "36763979244226452948404D635166546A576D5A7134743777217A25432A462D"